### ISSUE TITLE
Go version is old; so makefile init fails

### ISSUE THREAD

**Issue by steve78b** [hacs/development#3]
The gh build script uses go. It has been updated to support version 16, but go version 13 is installed (as part of the makefile). 

The base image points to the Alpine repositories version 13 (which has go version 13). This needs to be updated to version 14 (which has go version 16). 

I don't know where this should be fixed - perhaps a new base image? or maybe the makefile init should update the Alpine repositories locations before the 'apk add go' command?

**Comment by ludeeus** [comment]
Do not use this, use <https://hacs.xyz/docs/developer/start> instead
